spring:
  application:
    name: blog-article
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/article_db

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance_id:${random.value}}