spring:
  application:
    name: blog-security
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance_id:${random.value}}

jwt:
  key: KR+NTtQXmg11QLDbT3HIiQsei4WCPs8+hFaD3mgSTk0=
  expiration-time: 7200