spring:
  application:
    name: blog-gateway
  cloud:
    loadbalancer:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  key: KR+NTtQXmg11QLDbT3HIiQsei4WCPs8+hFaD3mgSTk0=