spring:
  application:
    name:blog-ai
  ai:
    vertex:
      ai:
        gemini:
          location: us-central1
          project-id: blog-ai-project
          chat:
            options:
              model: gemini-2.0-flash-lite-001
              temperature: 0.4

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance_id:${random.value}}